using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;

namespace SWEF.TimeCapsule
{
    /// <summary>
    /// Core singleton manager for the Time Capsule &amp; Memory system.
    /// Handles the full lifecycle of <see cref="TimeCapsule"/> records: creation, opening,
    /// deletion, sharing, and JSON persistence.
    /// </summary>
    [DefaultExecutionOrder(-35)]
    public class TimeCapsuleManager : MonoBehaviour
    {
        // ── Singleton ─────────────────────────────────────────────────────────────
        /// <summary>Global singleton instance.</summary>
        public static TimeCapsuleManager Instance { get; private set; }

        // ── Events ────────────────────────────────────────────────────────────────
        /// <summary>Fired after a new capsule is successfully created and sealed.</summary>
        public event Action<TimeCapsule> OnCapsuleCreated;

        /// <summary>Fired after a capsule is successfully opened.</summary>
        public event Action<TimeCapsule> OnCapsuleOpened;

        /// <summary>Fired after a capsule is marked as shared.</summary>
        public event Action<TimeCapsule> OnCapsuleShared;

        // ── Internal state ────────────────────────────────────────────────────────
        private List<TimeCapsule> _capsules = new List<TimeCapsule>();

        private static readonly string SaveFileName = "timecapsules.json";
        private string SavePath => Path.Combine(Application.persistentDataPath, SaveFileName);

        // ── Serialisation wrapper ─────────────────────────────────────────────────
        [Serializable]
        private class SaveData
        {
            public List<TimeCapsule> capsules = new List<TimeCapsule>();
        }

        // ── Public read-only access ───────────────────────────────────────────────
        /// <summary>Read-only view of all capsules held in memory.</summary>
        public IReadOnlyList<TimeCapsule> Capsules => _capsules;

        // ── Unity lifecycle ───────────────────────────────────────────────────────
        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
            DontDestroyOnLoad(gameObject);
            LoadFromJson();
        }

        private void OnApplicationPause(bool pauseStatus)
        {
            if (pauseStatus)
                SaveToJson();
        }

        private void OnApplicationQuit()
        {
            SaveToJson();
        }

        // ── CRUD ──────────────────────────────────────────────────────────────────

        /// <summary>
        /// Creates and seals a new <see cref="TimeCapsule"/> and adds it to the in-memory collection.
        /// </summary>
        /// <param name="title">Short display title.</param>
        /// <param name="description">Optional longer description.</param>
        /// <param name="type">Broad category for this capsule.</param>
        /// <param name="location">Geographic location snapshot.</param>
        /// <param name="weather">Weather conditions snapshot.</param>
        /// <param name="flight">Flight state snapshot.</param>
        /// <param name="screenshotPath">Absolute path to an associated screenshot, or empty.</param>
        /// <param name="tags">User-defined tags.</param>
        /// <param name="personalNote">Free-form personal note.</param>
        /// <param name="delayDays">Number of days before the capsule can be opened. 0 = immediately.</param>
        /// <param name="isAutoGenerated">Pass <c>true</c> when called by <see cref="TimeCapsuleAutoCapture"/>.</param>
        /// <returns>The newly created capsule.</returns>
        public TimeCapsule CreateCapsule(
            string title,
            string description,
            TimeCapsuleType type,
            CapsuleLocation location,
            CapsuleWeatherSnapshot weather,
            CapsuleFlightSnapshot flight,
            string screenshotPath,
            List<string> tags,
            string personalNote,
            float delayDays = 0f,
            bool isAutoGenerated = false)
        {
            var now = DateTime.UtcNow;
            var capsule = new TimeCapsule
            {
                capsuleId      = Guid.NewGuid().ToString(),
                title          = title,
                description    = description,
                type           = type,
                status         = TimeCapsuleStatus.Sealed,
                createdAt      = now.ToString("O"),
                openAfter      = now.AddDays(delayDays).ToString("O"),
                location       = location,
                weather        = weather,
                flight         = flight,
                screenshotPath = screenshotPath ?? string.Empty,
                tags           = tags ?? new List<string>(),
                personalNote   = personalNote ?? string.Empty,
                isAutoGenerated = isAutoGenerated
            };

            _capsules.Add(capsule);
            SaveToJson();
            OnCapsuleCreated?.Invoke(capsule);
            return capsule;
        }

        /// <summary>
        /// Attempts to open a sealed capsule. Succeeds only if the capsule exists, is
        /// <see cref="TimeCapsuleStatus.Sealed"/>, and <see cref="TimeCapsule.IsReadyToOpen"/> returns <c>true</c>.
        /// </summary>
        /// <param name="capsuleId">The GUID of the capsule to open.</param>
        /// <returns>The opened capsule, or <c>null</c> if the operation failed.</returns>
        public TimeCapsule OpenCapsule(string capsuleId)
        {
            var capsule = FindCapsule(capsuleId);
            if (capsule == null)
            {
                Debug.LogWarning($"[TimeCapsuleManager] OpenCapsule: capsule '{capsuleId}' not found.");
                return null;
            }
            if (capsule.status != TimeCapsuleStatus.Sealed)
            {
                Debug.LogWarning($"[TimeCapsuleManager] OpenCapsule: capsule '{capsuleId}' is not sealed (status={capsule.status}).");
                return null;
            }
            if (!capsule.IsReadyToOpen())
            {
                Debug.LogWarning($"[TimeCapsuleManager] OpenCapsule: capsule '{capsuleId}' is not ready to open yet.");
                return null;
            }

            capsule.status = TimeCapsuleStatus.Opened;
            SaveToJson();
            OnCapsuleOpened?.Invoke(capsule);
            return capsule;
        }

        /// <summary>
        /// Permanently removes a capsule from the in-memory collection and persists the change.
        /// </summary>
        /// <param name="capsuleId">The GUID of the capsule to delete.</param>
        /// <returns><c>true</c> if the capsule was found and removed; otherwise <c>false</c>.</returns>
        public bool DeleteCapsule(string capsuleId)
        {
            int removed = _capsules.RemoveAll(c => c.capsuleId == capsuleId);
            if (removed > 0)
            {
                SaveToJson();
                return true;
            }
            Debug.LogWarning($"[TimeCapsuleManager] DeleteCapsule: capsule '{capsuleId}' not found.");
            return false;
        }

        // ── Queries ───────────────────────────────────────────────────────────────

        /// <summary>Returns all capsules of the specified <paramref name="type"/>.</summary>
        public List<TimeCapsule> GetCapsulesByType(TimeCapsuleType type)
            => _capsules.Where(c => c.type == type).ToList();

        /// <summary>
        /// Returns all <see cref="TimeCapsuleStatus.Sealed"/> capsules for which
        /// <see cref="TimeCapsule.IsReadyToOpen"/> is <c>true</c>.
        /// </summary>
        public List<TimeCapsule> GetReadyCapsules()
            => _capsules.Where(c => c.status == TimeCapsuleStatus.Sealed && c.IsReadyToOpen()).ToList();

        // ── Social ────────────────────────────────────────────────────────────────

        /// <summary>Marks a capsule as <see cref="TimeCapsuleStatus.Shared"/>.</summary>
        /// <param name="capsuleId">The GUID of the capsule to share.</param>
        /// <returns>The capsule if found; otherwise <c>null</c>.</returns>
        public TimeCapsule ShareCapsule(string capsuleId)
        {
            var capsule = FindCapsule(capsuleId);
            if (capsule == null)
            {
                Debug.LogWarning($"[TimeCapsuleManager] ShareCapsule: capsule '{capsuleId}' not found.");
                return null;
            }

            capsule.status = TimeCapsuleStatus.Shared;
            SaveToJson();
            OnCapsuleShared?.Invoke(capsule);
            return capsule;
        }

        // ── Persistence ───────────────────────────────────────────────────────────

        /// <summary>Serializes the in-memory capsule list to <c>timecapsules.json</c>.</summary>
        public void SaveToJson()
        {
            try
            {
                var data = new SaveData { capsules = _capsules };
                string json = JsonUtility.ToJson(data, true);
                File.WriteAllText(SavePath, json);
            }
            catch (Exception ex)
            {
                Debug.LogError($"[TimeCapsuleManager] SaveToJson failed: {ex.Message}");
            }
        }

        /// <summary>Loads the capsule list from <c>timecapsules.json</c> if it exists.</summary>
        public void LoadFromJson()
        {
            if (!File.Exists(SavePath)) return;
            try
            {
                string json = File.ReadAllText(SavePath);
                var data = JsonUtility.FromJson<SaveData>(json);
                if (data?.capsules != null)
                    _capsules = data.capsules;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[TimeCapsuleManager] LoadFromJson failed: {ex.Message}");
            }
        }

        // ── Helpers ───────────────────────────────────────────────────────────────

        private TimeCapsule FindCapsule(string capsuleId)
            => _capsules.FirstOrDefault(c => c.capsuleId == capsuleId);
    }
}
