using System;
using System.Collections.Generic;
using UnityEngine;

namespace SWEF.Ocean
{
    #region Enumerations

    /// <summary>Classifies the type of a water body in the world.</summary>
    public enum WaterBodyType
    {
        /// <summary>Large salt-water expanse.</summary>
        Ocean,
        /// <summary>Enclosed or semi-enclosed sea.</summary>
        Sea,
        /// <summary>Inland standing water body.</summary>
        Lake,
        /// <summary>Flowing channel of fresh water.</summary>
        River,
        /// <summary>Small standing water body.</summary>
        Pond,
        /// <summary>Vertical drop of flowing water.</summary>
        Waterfall,
        /// <summary>Shallow wetland area.</summary>
        Swamp
    }

    /// <summary>Controls the fidelity of the Gerstner-wave vertex simulation.</summary>
    public enum WaveQuality
    {
        /// <summary>Single octave, no vertex displacement.</summary>
        Low,
        /// <summary>Two octaves, minimal displacement.</summary>
        Medium,
        /// <summary>Four octaves, full displacement.</summary>
        High,
        /// <summary>Eight octaves, full displacement + foam.</summary>
        Ultra
    }

    /// <summary>Selects the reflection rendering strategy for the water surface.</summary>
    public enum ReflectionMode
    {
        /// <summary>No reflections.</summary>
        None,
        /// <summary>Single planar reflection pass, reduced resolution.</summary>
        PlanarSimple,
        /// <summary>Full-resolution planar reflection.</summary>
        PlanarHQ,
        /// <summary>Screen-space reflection (requires compatible render pipeline).</summary>
        ScreenSpace,
        /// <summary>Baked or real-time cubemap reflection.</summary>
        CubeMap
    }

    /// <summary>Selects which foam effects are visible on the water surface.</summary>
    public enum FoamType
    {
        /// <summary>No foam rendered.</summary>
        None,
        /// <summary>Foam where water meets land.</summary>
        Shore,
        /// <summary>Foam in the wake of moving objects.</summary>
        Wake,
        /// <summary>Foam generated by storm conditions.</summary>
        Storm,
        /// <summary>White-cap foam on open-water crests.</summary>
        WhiteCap
    }

    /// <summary>Cardinal and inter-cardinal directions for water current flow.</summary>
    public enum WaterCurrentDirection
    {
        North,
        South,
        East,
        West,
        NorthEast,
        SouthEast,
        SouthWest,
        NorthWest,
        /// <summary>Direction defined by <see cref="OceanSettings.customCurrentDirection"/>.</summary>
        Custom
    }

    #endregion

    #region Wave & Appearance Settings

    /// <summary>
    /// Parameters that define a single wave octave in the Gerstner wave model.
    /// All octaves are combined to produce the final surface displacement.
    /// </summary>
    [Serializable]
    public class WaveParameters
    {
        /// <summary>Peak crest height above mean water level (metres).</summary>
        [Tooltip("Peak crest height above mean water level (metres).")]
        public float amplitude = 0.5f;

        /// <summary>Spatial frequency of the wave (cycles per metre).</summary>
        [Tooltip("Spatial frequency of the wave (cycles per metre).")]
        public float frequency = 0.1f;

        /// <summary>Phase speed of the wave (metres per second).</summary>
        [Tooltip("Phase speed of the wave (metres per second).")]
        public float speed = 1.5f;

        /// <summary>Horizontal propagation direction (XZ, need not be normalised).</summary>
        [Tooltip("Horizontal propagation direction (XZ).")]
        public Vector2 direction = new Vector2(1f, 0f);

        /// <summary>Sharpness of the wave crest (0 = sinusoidal, 1 = Gerstner).</summary>
        [Range(0f, 1f)]
        [Tooltip("Sharpness of the wave crest (0 = sinusoidal, 1 = trochoidal).")]
        public float steepness = 0.5f;

        /// <summary>Number of additive octaves to layer above this base wave.</summary>
        [Range(1, 8)]
        [Tooltip("Number of additive octaves (1–8).")]
        public int octaves = 4;
    }

    /// <summary>
    /// Visual properties that control how the water surface looks.
    /// </summary>
    [Serializable]
    public class WaterAppearance
    {
        /// <summary>Water colour in shallow areas.</summary>
        [Tooltip("Water colour in shallow areas.")]
        public Color shallowColor = new Color(0.1f, 0.6f, 0.7f, 0.8f);

        /// <summary>Water colour in deep areas.</summary>
        [Tooltip("Water colour in deep areas.")]
        public Color deepColor = new Color(0.03f, 0.15f, 0.35f, 1f);

        /// <summary>Overall water transparency (0 = opaque, 1 = fully transparent).</summary>
        [Range(0f, 1f)]
        [Tooltip("Overall water transparency.")]
        public float transparency = 0.4f;

        /// <summary>Strength of the underwater refraction distortion.</summary>
        [Range(0f, 2f)]
        [Tooltip("Strength of underwater refraction distortion.")]
        public float refractionStrength = 0.5f;

        /// <summary>Specular highlight intensity.</summary>
        [Range(0f, 2f)]
        [Tooltip("Specular highlight intensity.")]
        public float specularIntensity = 1.2f;

        /// <summary>Fresnel exponent — controls the viewing-angle roll-off of reflections.</summary>
        [Range(0.5f, 8f)]
        [Tooltip("Fresnel exponent (higher = sharper reflection at grazing angle).")]
        public float fresnelPower = 4f;

        /// <summary>Colour of surface foam.</summary>
        [Tooltip("Colour of surface foam.")]
        public Color foamColor = Color.white;

        /// <summary>Subsurface scattering tint for back-lit wave crests.</summary>
        [Tooltip("Subsurface scattering tint for back-lit wave crests.")]
        public Color subsurfaceScatteringColor = new Color(0.1f, 0.8f, 0.6f, 1f);
    }

    /// <summary>
    /// Settings that control the visual appearance of shorelines.
    /// </summary>
    [Serializable]
    public class ShorelineSettings
    {
        /// <summary>Horizontal width of the foam band at the waterline (metres).</summary>
        [Tooltip("Width of the foam band at the waterline (metres).")]
        public float foamWidth = 3f;

        /// <summary>Maximum opacity of the shore foam (0–1).</summary>
        [Range(0f, 1f)]
        [Tooltip("Maximum opacity of the shore foam.")]
        public float foamIntensity = 0.8f;

        /// <summary>Distance from shore at which incoming waves begin to break (metres).</summary>
        [Tooltip("Distance from shore at which incoming waves begin to break (metres).")]
        public float waveBreakDistance = 10f;

        /// <summary>Darkening multiplier applied to wet sand/rock near the waterline.</summary>
        [Range(0f, 1f)]
        [Tooltip("Darkening applied to wet terrain near the waterline.")]
        public float wetSandDarkeningRange = 0.3f;

        /// <summary>Phase speed of the animated shore-wave scroll (metres per second).</summary>
        [Tooltip("Phase speed of the animated shore-wave texture scroll.")]
        public float shoreWaveSpeed = 0.8f;
    }

    #endregion

    #region Body-Specific Settings

    /// <summary>
    /// Full configuration for an ocean or sea water body.
    /// </summary>
    [Serializable]
    public class OceanSettings
    {
        [Tooltip("Base wave parameters (amplitude, frequency, direction, etc.).")]
        public WaveParameters waves = new WaveParameters();

        [Tooltip("Surface appearance (colours, fresnel, foam, etc.).")]
        public WaterAppearance appearance = new WaterAppearance();

        [Tooltip("Shoreline foam and wave-break settings.")]
        public ShorelineSettings shoreline = new ShorelineSettings();

        [Tooltip("Wave simulation fidelity level.")]
        public WaveQuality waveQuality = WaveQuality.High;

        [Tooltip("Reflection rendering strategy.")]
        public ReflectionMode reflectionMode = ReflectionMode.PlanarSimple;

        /// <summary>Ambient wind speed driving wave generation (m/s, Beaufort-linked).</summary>
        [Tooltip("Ambient wind speed (m/s).")]
        public float windSpeed = 8f;

        /// <summary>Meteorological wind direction in degrees (0 = North, 90 = East).</summary>
        [Range(0f, 360f)]
        [Tooltip("Wind direction in degrees (0 = North, clockwise).")]
        public float windDirection = 270f;

        /// <summary>Speed of the prevailing surface current (m/s).</summary>
        [Tooltip("Speed of the prevailing surface current (m/s).")]
        public float currentSpeed = 0.3f;

        [Tooltip("Direction of the prevailing surface current.")]
        public WaterCurrentDirection currentDirection = WaterCurrentDirection.NorthEast;

        /// <summary>
        /// Custom current direction used when <see cref="currentDirection"/> is
        /// <see cref="WaterCurrentDirection.Custom"/>.
        /// </summary>
        [Tooltip("Custom current direction vector (XZ). Used when currentDirection == Custom.")]
        public Vector2 customCurrentDirection = Vector2.right;

        /// <summary>Maximum draw distance for the ocean surface (metres).</summary>
        [Tooltip("Maximum visible distance of the ocean surface (metres).")]
        public float maxVisibleDistance = 5000f;

        /// <summary>World-space side length of each ocean mesh tile (metres).</summary>
        [Tooltip("Side length of each ocean mesh tile (metres).")]
        public float tileSize = 256f;
    }

    /// <summary>
    /// Full configuration for a river or stream water body.
    /// </summary>
    [Serializable]
    public class RiverSettings
    {
        /// <summary>Flow speed along the spline (m/s).</summary>
        [Tooltip("Flow speed along the river spline (m/s).")]
        public float flowSpeed = 2f;

        /// <summary>Primary flow direction (world-space XZ unit vector).</summary>
        [Tooltip("Primary flow direction (world-space XZ unit vector).")]
        public Vector2 flowDirection = new Vector2(0f, -1f);

        /// <summary>Average river width (metres).</summary>
        [Tooltip("Average river width (metres).")]
        public float width = 20f;

        /// <summary>Average river depth (metres).</summary>
        [Tooltip("Average river depth (metres).")]
        public float depth = 2f;

        /// <summary>Turbulence intensity (0 = calm, 1 = rapids).</summary>
        [Range(0f, 1f)]
        [Tooltip("Turbulence intensity (0 = calm, 1 = rapids).")]
        public float turbulence = 0.2f;

        /// <summary>Whether foam should appear along the river banks.</summary>
        [Tooltip("Render foam along the river banks.")]
        public bool bankFoamEnabled = true;
    }

    #endregion

    #region Water Body Definition

    /// <summary>
    /// Describes a single water body that the <see cref="OceanManager"/> should track.
    /// </summary>
    [Serializable]
    public class WaterBodyDefinition
    {
        /// <summary>Unique identifier for this water body (GUID assigned at creation).</summary>
        public string id = Guid.NewGuid().ToString();

        /// <summary>Human-readable name (e.g. "Pacific Ocean", "Amazon River").</summary>
        public string displayName = "Water Body";

        /// <summary>Category of this water body.</summary>
        public WaterBodyType bodyType = WaterBodyType.Ocean;

        /// <summary>World-space centre position of the water body.</summary>
        public Vector3 worldPosition = Vector3.zero;

        /// <summary>
        /// For bounded bodies (lakes, ponds): XZ half-extents in metres.
        /// For infinite oceans: set to Vector2.zero to indicate unbounded.
        /// </summary>
        public Vector2 bounds = Vector2.zero;

        /// <summary>Radius for circular water bodies (lakes, ponds, swamps) in metres.</summary>
        public float radius = 500f;

        /// <summary>Ocean/sea-specific parameters (null for rivers).</summary>
        public OceanSettings oceanSettings = new OceanSettings();

        /// <summary>River/stream-specific parameters (null for oceans).</summary>
        public RiverSettings riverSettings = new RiverSettings();

        /// <summary>Whether this water body is currently active and should be rendered.</summary>
        public bool enabled = true;

        // ── Serialization helpers ────────────────────────────────────────────────

        /// <summary>Serialises this definition to a JSON string.</summary>
        public string ToJson() => JsonUtility.ToJson(this, prettyPrint: true);

        /// <summary>Populates this definition from a JSON string produced by <see cref="ToJson"/>.</summary>
        public void FromJson(string json) => JsonUtility.FromJsonOverwrite(json, this);
    }

    #endregion
}
