name: Acquire Unity License
on:
  workflow_dispatch: {}

jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-license-activate@v1
        with:
          unity-version: 6000.3.11f1
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}
      # 활성화 후 생성된 .ulf 파일을 아티팩트로 다운로드
